/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('business').del();
  await knex('business').insert([
    { category_id: 1, business_name: 'GreenThumb Landscaping', email: 'greenthumb@landscaping.com', phone_no: '123-456-7890', mission_statement: 'Designing beautiful outdoor spaces.', location: 'Vancouver, BC', linkedin_address: 'https://linkedin.com/greenthumb', instagram_handle: '@greenthumb', verification_status: true, overall_rating: 4.7, services_offered: 'Garden design, Lawn maintenance, Tree planting' },
    { category_id: 1, business_name: 'Urban Gardens', email: 'urbangardens@landscaping.com', phone_no: '234-567-8901', mission_statement: 'Greening the urban space.', location: 'Toronto, ON', linkedin_address: 'https://linkedin.com/urbangardens', instagram_handle: '@urbangardens', verification_status: false, overall_rating: 4.3, services_offered: 'Landscape design, Lawn care, Mulching' },
    { category_id: 1, business_name: 'Blooming Landscapes', email: 'blooming@landscaping.com', phone_no: '345-678-9012', mission_statement: 'Bringing beauty to your backyard.', location: 'Montreal, QC', linkedin_address: 'https://linkedin.com/blooming', instagram_handle: '@bloominglandscapes', verification_status: true, overall_rating: 4.8, services_offered: 'Planting, Irrigation, Hardscaping' },
    { category_id: 1, business_name: 'Nature’s Touch', email: 'naturestouch@landscaping.com', phone_no: '456-789-0123', mission_statement: 'Designing nature-inspired spaces.', location: 'Calgary, AB', linkedin_address: 'https://linkedin.com/naturestouch', instagram_handle: '@naturestouch', verification_status: true, overall_rating: 4.6, services_offered: 'Garden design, Lawn care, Shrub trimming' },
    { category_id: 1, business_name: 'Lush Landscapes', email: 'lushlandscapes@landscaping.com', phone_no: '567-890-1234', mission_statement: 'Creating lush, vibrant landscapes.', location: 'Ottawa, ON', linkedin_address: 'https://linkedin.com/lushlandscapes', instagram_handle: '@lushlandscapes', verification_status: false, overall_rating: 4.4, services_offered: 'Lawn care, Tree planting, Garden maintenance' },
 
    { category_id: 2, business_name: 'FixIt All Renovations', email: 'fixitall@renovations.com', phone_no: '678-901-2345', mission_statement: 'Your go-to experts for home repairs and renovations.', location: 'Vancouver, BC', linkedin_address: 'https://linkedin.com/fixitall', instagram_handle: '@fixitall', verification_status: true, overall_rating: 4.9, services_offered: 'General home repairs, Kitchen remodel, Bathroom renovations' },
    { category_id: 2, business_name: 'Next Level Renovations', email: 'nextlevel@renovations.com', phone_no: '789-012-3456', mission_statement: 'Taking your home to the next level.', location: 'Toronto, ON', linkedin_address: 'https://linkedin.com/nextlevel', instagram_handle: '@nextlevel', verification_status: false, overall_rating: 4.1, services_offered: 'Home addition, Basement finishing, Flooring' },
    { category_id: 2, business_name: 'Elite Home Renovators', email: 'elitehome@renovations.com', phone_no: '890-123-4567', mission_statement: 'Quality home renovations that last a lifetime.', location: 'Montreal, QC', linkedin_address: 'https://linkedin.com/elitehome', instagram_handle: '@elitehome', verification_status: true, overall_rating: 4.7, services_offered: 'General renovations, Roofing, Electrical work' },
    { category_id: 2, business_name: 'Total Home Makeovers', email: 'totalhome@renovations.com', phone_no: '901-234-5678', mission_statement: 'Making your dream home a reality.', location: 'Calgary, AB', linkedin_address: 'https://linkedin.com/totalhome', instagram_handle: '@totalhome', verification_status: true, overall_rating: 4.8, services_offered: 'Kitchen remodel, Bathroom upgrade, Drywall installation' },
    { category_id: 2, business_name: 'House Smart Renovations', email: 'housesmart@renovations.com', phone_no: '012-345-6789', mission_statement: 'Innovative home solutions and repairs.', location: 'Ottawa, ON', linkedin_address: 'https://linkedin.com/housesmart', instagram_handle: '@housesmart', verification_status: false, overall_rating: 4.4, services_offered: 'Home repairs, Painting, Custom cabinetry' },
 
    { category_id: 3, business_name: 'QuickMove', email: 'quickmove@moving.com', phone_no: '112-334-5566', mission_statement: 'Fast and reliable moving services.', location: 'Vancouver, BC', linkedin_address: 'https://linkedin.com/quickmove', instagram_handle: '@quickmove', verification_status: true, overall_rating: 4.8, services_offered: 'Residential moving, Office relocation, Furniture delivery' },
    { category_id: 3, business_name: 'Pack and Go Movers', email: 'packandgo@moving.com', phone_no: '223-445-6677', mission_statement: 'Stress-free moving, every time.', location: 'Toronto, ON', linkedin_address: 'https://linkedin.com/packandgo', instagram_handle: '@packandgo', verification_status: false, overall_rating: 4.4, services_offered: 'Packing, Furniture delivery, Small moves' },
    { category_id: 3, business_name: 'OnTime Moving', email: 'ontimemove@moving.com', phone_no: '334-556-7788', mission_statement: 'We move your world, on time.', location: 'Montreal, QC', linkedin_address: 'https://linkedin.com/ontimemove', instagram_handle: '@ontimemove', verification_status: true, overall_rating: 4.7, services_offered: 'Long distance moving, Local moving, Heavy lifting' },
    { category_id: 3, business_name: 'Smooth Relocation', email: 'smoothrelocate@moving.com', phone_no: '445-667-8899', mission_statement: 'Smooth moving, guaranteed.', location: 'Calgary, AB', linkedin_address: 'https://linkedin.com/smoothrelocation', instagram_handle: '@smoothrelocate', verification_status: true, overall_rating: 4.6, services_offered: 'Office moves, Apartment relocation, Vehicle transportation' },
    { category_id: 3, business_name: 'Swift Movers', email: 'swiftmovers@moving.com', phone_no: '556-778-9900', mission_statement: 'Quick, efficient, and affordable moving.', location: 'Ottawa, ON', linkedin_address: 'https://linkedin.com/swiftmovers', instagram_handle: '@swiftmovers', verification_status: false, overall_rating: 4.3, services_offered: 'Furniture delivery, Packing, Short-distance moving' },

    { category_id: 4, business_name: 'DriveEasy Rentals', email: 'driveeasy@carrentals.com', phone_no: '667-889-0011', mission_statement: 'Rent a car with ease.', location: 'Vancouver, BC', linkedin_address: 'https://linkedin.com/driveeasy', instagram_handle: '@driveeasy', verification_status: true, overall_rating: 4.7, services_offered: 'Car rentals, SUV rentals, Luxury vehicle rentals' },
    { category_id: 4, business_name: 'FastRent Cars', email: 'fastrent@carrentals.com', phone_no: '778-990-1122', mission_statement: 'Rent your dream car today.', location: 'Toronto, ON', linkedin_address: 'https://linkedin.com/fastrent', instagram_handle: '@fastrent', verification_status: false, overall_rating: 4.5, services_offered: 'Compact car rentals, Van rentals, Car delivery' },
    { category_id: 4, business_name: 'GoCar Rentals', email: 'gocar@carrentals.com', phone_no: '889-101-2233', mission_statement: 'Rent a car, go anywhere.', location: 'Montreal, QC', linkedin_address: 'https://linkedin.com/gocar', instagram_handle: '@gocar', verification_status: true, overall_rating: 4.8, services_offered: 'Convertible rentals, Family car rentals, Long-term rentals' },
    { category_id: 4, business_name: 'Elite Auto Rentals', email: 'eliteauto@carrentals.com', phone_no: '990-112-3344', mission_statement: 'Rent premium vehicles for any occasion.', location: 'Calgary, AB', linkedin_address: 'https://linkedin.com/eliteauto', instagram_handle: '@eliteauto', verification_status: true, overall_rating: 4.6, services_offered: 'Luxury car rentals, Sedan rentals, Exotic car rentals' },
    { category_id: 4, business_name: 'Affordable Ride Rentals', email: 'affordableride@carrentals.com', phone_no: '112-223-4455', mission_statement: 'Affordable rides, exceptional service.', location: 'Ottawa, ON', linkedin_address: 'https://linkedin.com/affordableride', instagram_handle: '@affordableride', verification_status: false, overall_rating: 4.4, services_offered: 'Economy car rentals, Truck rentals, Weekend deals' },

    { category_id: 5, business_name: 'Decor Magic', email: 'decormagic@decor.com', phone_no: '223-334-4455', mission_statement: 'Bringing style to every home.', location: 'Vancouver, BC', linkedin_address: 'https://linkedin.com/decormagic', instagram_handle: '@decormagic', verification_status: true, overall_rating: 4.9, services_offered: 'Interior design, Furniture selection, Lighting design' },
    { category_id: 5, business_name: 'Home Harmony', email: 'harmony@decor.com', phone_no: '334-445-5566', mission_statement: 'Creating spaces that feel like home.', location: 'Toronto, ON', linkedin_address: 'https://linkedin.com/homeharmony', instagram_handle: '@homeharmony', verification_status: false, overall_rating: 4.6, services_offered: 'Home staging, Space planning, Wall art selection' },
    { category_id: 5, business_name: 'Urban Chic Interiors', email: 'urbanchic@decor.com', phone_no: '445-556-6677', mission_statement: 'Making your space as unique as you.', location: 'Montreal, QC', linkedin_address: 'https://linkedin.com/urbanchic', instagram_handle: '@urbanchic', verification_status: true, overall_rating: 4.7, services_offered: 'Color consultation, Custom furniture, Window treatments' },
    { category_id: 5, business_name: 'Elegant Interiors', email: 'elegant@decor.com', phone_no: '556-667-7788', mission_statement: 'Elevating your home’s style.', location: 'Calgary, AB', linkedin_address: 'https://linkedin.com/elegantinteriors', instagram_handle: '@elegantinteriors', verification_status: true, overall_rating: 4.8, services_offered: 'Interior design, Home makeovers, Vintage furnishings' },
    { category_id: 5, business_name: 'Modern Living Interiors', email: 'modernliving@decor.com', phone_no: '667-778-8899', mission_statement: 'Modern designs for contemporary living.', location: 'Ottawa, ON', linkedin_address: 'https://linkedin.com/modernliving', instagram_handle: '@modernliving', verification_status: false, overall_rating: 4.3, services_offered: 'Minimalist design, Smart home installations, Lighting solutions' },
  ]);
};
